export type Contact = {
    birthday?: string;
    businessAddress?: { [key: string]: string };
    businessHomePage?: string;
    businessPhones?: Array<string>;
    categories?: Array<string>;
    changeKey?: string;
    children?: Array<string>;
    companyName?: string;
    createdDateTime?: string;
    department?: string;
    displayName?: string;
    emailAddresses?: { [key: string]: string };
    generation?: string;
    givenName?: string;
    homeAddress?: { [key: string]: string };
    homePhones?: Array<string>;
    id?: string;
    imAddresses?: Array<string>;
    initials?: string;
    jobTitle?: string;
    lastModifiedDateTime?: string;
    manager?: string;
    middleName?: string;
    mobilePhone?: string;
    nickName?: string;
    officeLocation?: string;
    otherAddress?: { [key: string]: string };
    parentFolderId?: string;
    personalNotes?: string;
    profession?: string;
    surname?: string;
    title?: string;
};