# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of .net

name: ".NET Build"

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - run: |
        cd 3-Authorization-II/1-call-api/API
        dotnet restore
        dotnet build --no-restore
        cd TodoListAPI.Tests
        dotnet test --no-build --verbosity normal

    - run: |
        cd 3-Authorization-II/2-call-api-b2c/API
        dotnet restore
        dotnet build --no-restore
        cd TodoListAPI.Tests
        dotnet test --no-build --verbosity normal

    - run: |
        cd 5-AccessControl/1-call-api-roles/API
        dotnet restore
        dotnet build --no-restore
        cd TodoListAPI.Tests
        dotnet test --no-build --verbosity normal

    - run: |
        cd 7-AdvancedScenarios/1-call-api-obo/API
        dotnet restore
        dotnet build --no-restore
        cd ProfileAPI.Tests
        dotnet test --no-build --verbosity normal